# Generated by Django 5.2.7 on 2025-11-03 02:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codeudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], default='CEDULA', max_length=20, verbose_name='Tipo de Documento')),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('relationship', models.CharField(blank=True, help_text='Ej: Esposo/a, Familiar, Amigo, etc.', max_length=100, verbose_name='Parentesco/Relación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codeudores', to='authentication.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Codeudor',
                'verbose_name_plural': 'Codeudores',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'document_number')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='codeudor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='users.codeudor', verbose_name='Codeudor'),
        ),
    ]
