# Generated by Django 5.2.7 on 2025-11-03 02:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto del Préstamo')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tasa de Interés (%)')),
                ('payment_frequency', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=20, verbose_name='Frecuencia de Pago')),
                ('total_payments', models.PositiveIntegerField(verbose_name='Número de Pagos')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='authentication.tenant', verbose_name='Tenant')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.userprofile', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-created_at'],
            },
        ),
    ]
