# Generated by Django 5.2.7 on 2025-11-04 00:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto (Opcional)')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tasa de Interés (%)')),
                ('payment_frequency', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=20, verbose_name='Frecuencia de Pago')),
                ('total_payments', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Pagos (Opcional)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_templates', to='authentication.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Plantilla de Préstamo',
                'verbose_name_plural': 'Plantillas de Préstamos',
                'ordering': ['name'],
            },
        ),
    ]
